config/routes.rb
ProjectManagement::Application.routes.draw do
  resources :topics

  resources :projects

  resources :discussions

  resources :todos
 
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

    namespace :mercury do
      resources :images
    end

  mount Mercury::Engine => '/'

  get "access/menu"

  get "access/login"

  get "acsess/menu"

  get "acsess/manu"

  get "acsess/login"

  resources :blogs

  resources :user_records

  resources :statuses

  devise_for :users , :path_names => {:sign_up => 'register'}

   match ':controller(/:action(/:id))(.:format)'
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  attr_accessible :test, :title
end

app/models/discussion.rb
class Discussion < ActiveRecord::Base
   attr_accessible  :user_id, :name, :started_by, :project_id, :topic_id,:parent_id
   belongs_to :topic, :foreign_key => :topic_id
   belongs_to :project
   belongs_to :user

   has_ancestry

   scope :search, lambda {|query| where(["started_by LIKE ?", "%#{query}%"])}
   
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_event_calendar
end

app/models/project.rb
class Project < ActiveRecord::Base
   attr_accessible :image, :remote_image_url,:project_name, :estimeted_complete_date,
   :done, :resources, :project_manager_name, :cost, :user_id, :email, :id,
    :username, :project_topics, :project_id, :text_document, :dates, :events
    belongs_to :user
     has_many :discussions
     has_many :todos
     has_many :topics
     has_many :add_user_to_projects
     mount_uploader :image, ImageUploader
      

      def username
      	if @user_id
			@user=User.find_by_username(:username)
			return @user
		else
			false
		end
      end
       def self.text_search(query)
      if query.present?
        # where("project_name ilike :q ", q => "%#{query}%")
        find(:all, :conditions => ['project_name LIKE ?', "%#{query}%"])
        #search(query)
      else
        scoped
      end
     end
      def self.user_search(query)
      if query.present?
        # where("project_name ilike :q ", q => "%#{query}%")
        find(:all, :conditions => ['email LIKE or username LIKE ?', "%#{query}%"])
        #search(query)
      else
        scoped
      end
     end
 end

app/models/status.rb
class Status < ActiveRecord::Base
  attr_accessible :project_name, :body
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  attr_accessible :add, :visible, :priority, :created_at, :project_id, :topic_id, :status
  belongs_to :project
  belongs_to :topic
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  attr_accessible :project_id, :topic_name, :topic_id
  belongs_to :project
  has_many :discussions, :foreign_key => :topic_id
  has_many :todos
end

app/models/user.rb
require 'digest/sha1'
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username, :birthday,
  :first_name, :last_name,:phone_no, :location, :image, :user_id
  # attr_accessible :title, :body
  has_many :projects
  has_many :topics
  has_many :discussions
  has_many :todos
  belongs_to :add_user_to_project
  mount_uploader :image,ImageUploader

   def devise_mailer
    UserMailer
  end

end

app/models/user_record.rb
class UserRecord < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  # GET /statuses
  # GET /statuses.json
  before_filter :authenticate_user!
  def index
    @add_users=AddUserToProject.order("add_more_user ASC" )
    current_user_id=User.where(@user)
    @project=Project.where(:user_id => current_user)

    @statuses = Status.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @statuses }
    end

  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
    @status = Status.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @status }
    end
  end

  # GET /statuses/new
  # GET /statuses/new.json
  def new
    @status = Status.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @status }
    end
  end

  # GET /statuses/1/edit
  def edit
    @status = Status.find(params[:id])
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = Status.new(params[:status])

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, :notice => 'Status was successfully created.' }
        format.json { render :json => @status, :status => :created, :location => @status }
      else
        format.html { render :action => "new" }
        format.json { render :json => @status.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /statuses/1
  # PUT /statuses/1.json
  def update
    @status = Status.find(params[:id])

    respond_to do |format|
      if @status.update_attributes(params[:status])
        format.html { redirect_to @status, :notice => 'Status was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @status.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status = Status.find(params[:id])
    @status.destroy

    respond_to do |format|
      format.html { redirect_to statuses_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/access_helper.rb
module AccessHelper
end

app/helpers/acsess_helper.rb
module AcsessHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
  def month_link(month_date)
    link_to(I18n.localize(month_date, :format => "%B"), {:month => month_date.month, :year => month_date.year})
  end
  
  # custom options for this calendar
  def event_calendar_opts
    { 
      :year => @year,
      :month => @month,
      :event_strips => @event_strips,
      :month_name_text => I18n.localize(@shown_month, :format => "%B %Y"),
      :previous_month_text => "<< " + month_link(@shown_month.prev_month),
      :next_month_text => month_link(@shown_month.next_month) + " >>"    }
  end

  def event_calendar
    # args is an argument hash containing :event, :day, and :options
    calendar event_calendar_opts do |args|
      event = args[:event]
      %(<a href="/events/#{event.id}" title="#{h(event.name)}">#{h(event.name)}</a>)
    end
  end
end

app/helpers/discussion_helper.rb
module DiscussionHelper
	def nested_messages(messages)
		messages.map do |message, sub_messages|
			render(message) + content_tag(:div, nested_messages(sub_messages), :class => "nested_messages")
	end.join.html_safe
end
end

app/helpers/explore_helper.rb
module ExploreHelper
end

app/helpers/project_helper.rb
module ProjectHelper

	def status_tag(boolean, options={})
		options[:true]  	  ||= ''
		options[:true_class]  ||= 'status true'
		options[:flase] 	  ||= ''
		options[:false_class] ||= 'status false'
		if boolean
			content_tag(:span, options[:true], :class => options[:true_class])
		else
			content_tag(:span, options[:false], :class => options[:false_class])
		end
	end
end

app/helpers/status_helper.rb
module StatusHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/todo_helper.rb
module TodoHelper
end

app/helpers/topic_helper.rb
module TopicHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/statuses/_form.html.erb
<%= form_for(@status) do |f| %>
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% @status.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/statuses/index.html.erb
<div class="/navbar-inner">
    <div class="/container">
      <a class="/btn btn-navbar" data-toggle="collapse"
      data-target=".nav-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </a>
    <a class="brand" href="#">PMS</a>
    <div class="nav-collapse">
      <ul class="nav">
       <a>
       <!--<%= link_to h(image_tag 'rails.png'), {:controller => 'project',:action => 'index'}%>-->

         <%= link_to 'Project',{:controller => 'project',:action => 'index'} %>
         |
         <%= link_to 'Calender', {:controller => 'calendar',:action => 'index'}%>
         |
         <%= link_to 'My Blog',{:controller => 'blogs', :action => 'index'}%>
         |
          <%= link_to 'Edit your Account', {:controller => 'users', :action => 'edit'}%>
          |
          <%= link_to 'Status',{:controller => 'statuses',:action => 'index'} %>
          | 
        
      <% if user_signed_in?%>
      <!-- Signed in as--> <%= current_user.first_name + " " + current_user.last_name %><%= image_tag current_user.image_url(:thumb).to_s%> Not you?
       <%= link_to "Sign out", destroy_user_session_path, :method => 'delete' %>
           <% else %>
    <%= link_to "Sign up"%> or <%= link_to "sign in",new_user_session_path%>
      <%end%>
       </a>
     </ul>
     </div>
     </div>
     </div>
     </div>
<h1>Activities</h1>
<!--
<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @statuses.each do |status| %>
  <tr>
    <td><%= link_to 'Show', status %></td>
    <td><%= link_to 'Edit', edit_status_path(status) %></td>
    <td><%= link_to 'Destroy', status, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />-->
<table>
  <tr>
    <ul>
<% @project.each do |f| %>
<hr>
<li>  <%= f.project_name %><a> is created by </a><%= current_user.first_name + " " + current_user.last_name%> <%= f.created_at%> </li>
  <%end%>

 
<hr>
<ul>
<li><%= current_user.first_name + " " + current_user.last_name%> added new user 
   <% @add_users.each do |p|%>
      <%= p.add_more_user%>
        to 
    <%= p.created_at%> <%end%></li>
</ul>
</tr>
</table>

app/views/statuses/new.html.erb
<h1>New status</h1>

<%= render 'form' %>

<%= link_to 'Back', statuses_path %>