config/routes.rb
ProjectManagement::Application.routes.draw do
  resources :topics

  resources :projects

  resources :discussions

  resources :todos
 
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

    namespace :mercury do
      resources :images
    end

  mount Mercury::Engine => '/'

  get "access/menu"

  get "access/login"

  get "acsess/menu"

  get "acsess/manu"

  get "acsess/login"

  resources :blogs

  resources :user_records

  resources :statuses

  devise_for :users , :path_names => {:sign_up => 'register'}

   match ':controller(/:action(/:id))(.:format)'
end

app/models/project.rb
class Project < ActiveRecord::Base
   attr_accessible :image, :remote_image_url,:project_name, :estimeted_complete_date,
   :done, :resources, :project_manager_name, :cost, :user_id, :email, :id,
    :username, :project_topics, :project_id, :text_document, :dates, :events
    belongs_to :user
     has_many :discussions
     has_many :todos
     has_many :topics
     has_many :add_user_to_projects
     mount_uploader :image, ImageUploader
      

      def username
      	if @user_id
			@user=User.find_by_username(:username)
			return @user
		else
			false
		end
      end
       def self.text_search(query)
      if query.present?
        # where("project_name ilike :q ", q => "%#{query}%")
        find(:all, :conditions => ['project_name LIKE ?', "%#{query}%"])
        #search(query)
      else
        scoped
      end
     end
      def self.user_search(query)
      if query.present?
        # where("project_name ilike :q ", q => "%#{query}%")
        find(:all, :conditions => ['email LIKE or username LIKE ?', "%#{query}%"])
        #search(query)
      else
        scoped
      end
     end
 end

app/controllers/project_controller.rb
class ProjectController < ApplicationController
	respond_to :html, :json
	layout 'application'

    before_filter :authenticate_user!

    before_filter :find_user
	before_filter :find_project
	before_filter :find_topic

	
	def create_topics
		#@project=Project.order("projects.created_at ASC").where(:project_id => @project.id)
		#@project=Project.find_by_id(@project.id)
		@topic=Topic.new(params[:topic])
	  
	  	 if  @topic.save
      redirect_to  :controller => 'project',:action => 'project_name',
       	 		:project_id => @topic.project_id
 
  end
	end

	def project_name
		#@project=Project.new
		
		@project_undertaken=Project.where(:user_id => current_user)
				@add_users=AddUserToProject.where(:project_id => @project)
	 @topic = Topic.new(:project_id => @project.id)
		@projects=Project.order("projects.created_at ASC").where(:id => @project.id)
		
		  @topics=Topic.where(:project_id => @project)


		 # @discussions=Discussion.find_by_sql("SELECT DISTINCT(discussions.topic_id),name FROM discussions
     #CROSS JOIN topics  WHERE discussions.topic_id=topics.id ")
		  @discussions=Discussion.scoped.where( :topic_id => @topic_id)
   @todos=Todo.find_by_sql("SELECT * FROM todos
     CROSS JOIN topics  WHERE todos.topic_id=topics.id ")
	
		  @discussion = Discussion.new
		 @todo = Todo.new
		 #@topic = Topic.new(:project_id => @project.id)
		#@topics=Topic.order("topics.created_at ASC")
		@user=User.new
		@users=User.order('email ASC')

		if @query = params[:query]  
       @project = Project.user_search(@query)
   end
	end

	def index
		@add_users=AddUserToProject.where(:project_id => @project)
		@projects=Project.new
		@discussion=Discussion.order('created_at asc').where(:topic_id => @topics)
		#@projects=Project.order("projects.created_at ASC").where(:project_id => @project)
        @topics=Topic.order('created_at asc').where(:project_id => '1')
			current_user_id=User.where(@user)
		@project=Project.where(:user_id => current_user)
		@user=User.order("email ASC")
		#@project=Project.order("projects.created_at ASC")
		if @query = params[:query]  
       @project = Project.text_search(@query)
   end
	end


	def new
		@project = Project.new
		@user=User.order("email ASC")
	end

	def show
			current_user_id=User.where(@user)
		@project=Project.where(:user_id => current_user)
		#@project=Project.order("projects.created_at ASC")
		@user=User.order("usernames ASC")
	end

	def create
		@project= Project.new(params[:project])
		if @project.save
			
			redirect_to(:action => 'index')
		else
			render 'new'
		end
	end
	def create_discussion
    	    @discussion=Discussion.new(params[:discussion])
		if @discussion.save
			render :partial => 'shared/discussion', :object => @discussion
	 		#redirect_to(:action => 'list', :topic_id => @discussion.topic.id )
		else
      		render('list')
		end
	end

		def save_todo
    	@todo=Todo.new(params[:todo])
	if @todo.save
		
	  redirect_to :controller => 'project',:action => 'index'
	
	else
      render('list')
	end
end
 
 def create_todo
    	@todo=Todo.new(params[:todo])
	if @todo.save
	render :partial => 'shared/todo', :object => @todo
	
	
	else
      render('list')
	end
end


	def edit
		@project=Project.find(params[:id])
		@user=User.order("email ASC")
	end

	def update
		  @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, :notice => 'Blog was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @project.errors, :status => :unprocessable_entity }
     end
    end
		#if @project.update_attributes(params[:project])
			#redirect_to(:action => 'show', :id => @project.id)
			
		#else
			#render('edit')
		#end
	end

	def home
		redirect_to("http://localhost:3000")
	end

	def delete
		@project=Project.find(params[:id])
	end

	def destroy
		@project = Project.find(params[:id])
		@project.destroy
		flash[:notice] = "Project destroyed."
		redirect_to(:action => 'show')
	end
	def document
			@project=Project.scoped
	end
	

	def add_user
		@add_user=AddUserToProject.new(params[:add_user_to_projects])
		if @add_user.save	
			redirect_to :controller => "project",:action => "project_name",:project_id => @add_user.project_id
		end
	end

private
	def find_project
		if params[:project_id]
			@project=Project.find_by_id(params[:project_id])
		end
	end
	def find_topic
		if params[:topic_id]
			@topic=Topic.find_by_id(params[:topic_id])
		end
	end

	def find_user
		if params[:user_id]
			@user=User.find_by_id(params[:user_id])

		end
	end

	

#calender
	def calendar
		@project=Project.this_month
		@date=Date.today
	end
end

app/helpers/project_helper.rb
module ProjectHelper

	def status_tag(boolean, options={})
		options[:true]  	  ||= ''
		options[:true_class]  ||= 'status true'
		options[:flase] 	  ||= ''
		options[:false_class] ||= 'status false'
		if boolean
			content_tag(:span, options[:true], :class => options[:true_class])
		else
			content_tag(:span, options[:false], :class => options[:false_class])
		end
	end
end

app/views/project/_document.html.erb
<li>Text Documents</li>
	<%= form_for :project do |f|%>

<%= f.file_field :text_document%>
<%end%>

app/views/project/_form.html.erb
    <td><%=h topic.topic_name %></td>
    <td><%=h link_to 'Destroy', topic, :method => :delete, data: { confirm: 'Are you sure?' } %></td>

app/views/project/_newuser.html.erb
<!--<%= form_for @user, :url => {:action => 'add_user'} do |p|%>
<%=  text_field_tag :query, params[:query]%>
<%= submit_tag "Search", :name => 'search by name or email'%>
<%= p.select(:email, @users.collect{|s| [s.email]})%>
<%= p.submit ('Add User')%>
<%end%>-->

<%= form_for :add_user_to_projects, :url => {:action => 'add_user'},:project_id => @project.id do |p|%>
<%= p.select(:project_id, @projects.collect{|s| [s.id]})%>

<%= p.text_field :add_more_user %>
<%= p.submit ('Add User')%>
<%end%>

app/views/project/_topic.html.erb
  <%= form_for :topic, :url => {:action => 'create_topic'},:project_id => @project.id,:remote => true do |f| %>
  
    
  <ul>
     <li id="/hide"><%= f.select(:project_id, @projects.collect {|s| [s.id]})%></td>
  
    <li><%= f.label(:topic_name) %></th>
    <li><%= f.text_field(:topic_name) %></td>
  </ul>

   
      <%= f.submit "Add new topic" %>
   
  <% end %>

app/views/project/calendar.html.erb
<div id="calendar">
	<h2 id="month">
    <%= link_to "<", :month => (Date.today.beginning_of_month-1).strftime("%Y-%m")%>
    <%=h Date.today.strftime("%B %Y")%>
    <%= link_to ">", :month => (Date.today.end_of_month+1).strftime("%Y-%m")%>
	</h2>
<%= calendar_for @project,:year => Date.today.year,:month => Date.today.month do |t| %>
  <%= t.head('mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun') %>
  <%= t.day do |day, project_name| %>
    <%= day.day %>
    <% project_name.each do |project| %>
      <%= h(project.name) %>
    <% end %>
  <% end %>
<% end %>

</div> 

app/views/project/delete.html.erb
<%= link_to("<< Back to Show",{:action => 'show'}, :class => 'back-link')%>

<div class="subject delete">
	<h2>Delete Subject</h2>
<%= form_for(:project, :url => {:action => 'destroy', :id => @project.id}) do |f|%>
<p>Are you sure you want to permanently delete this project?</p>
	<p class="reference-name"><%= @project.project_name%></p>
	<div class="form-buttons">
		<%= submit_tag("Delete Project")%>
	</div>
	<%end%>
</div>

app/views/project/document.html.erb
<h1>Documents</h1><a>delete</a><a>move from one project to other</a>
<div id="text-document">
<div id="primary" data-mercury="full">
  default content
</div>
</div>
<a>Tell something about this document</a>

<%= link_to 'Edit Page',"/editor" + request.path%>
<%= link_to "<< Back to Project",:controller => "project",:action => "index"%>

app/views/project/edit.html.erb
<!--<div id= "navi">
  <div id="/aside">
    <h1>project</h1>
</div>-->
<td><%= best_in_place @project,:project_name%></td> 
<div id="/background">
<a>here is a brief description how to create a project</a>
<div class="project">
  
	<%= form_for(:project, :url => {:action => 'update', :id => @project.id}) do |f| %>
	<table>
	<tr>
		<th>Project Name</th>
		<td><%= f.text_field(:project_name)%></td>
	</tr>
	<tr>
    	 <th><%= f.label :estimated_complete_date%></th>
     <!-- <td><%= datepicker_input "f","estimeted_complete_date", :class => 'ui-timepicker-div'%> </td>-->
        <td><%= f.text_field :estimeted_complete_date%></td>
    </tr>
    <tr>
    	 <th>Done</th>
    	 <td><%= f.check_box(:done)%></td>
    </tr>
    <tr>
    	 <th>People Involvement</th>
    	 <td><%= f.text_field(:resources)%></td>
    </tr>
    <tr>
    	 <th>Project Manager Name</th>
    	 <td><%= f.text_field(:project_manager_name)%></td>
    </tr>
    <tr>
    	 <th>Cost</th>
    	 <td><%= f.text_field(:cost)%></td>
	</tr>
    <th><%= f.label(:user_id, "Add more User") %></th>
    <td><%= f.select(:user_id, @user.collect {|s| [s.username, s.id]}) %></td>

     <tr>
         <th>Upload</th>
         <td><%= f.file_field :image %></td>
    </tr> 
       <tr>
    <th><%= f.label :remote_image_url, "or image URL" %></th>
    <th><%= f.text_field :remote_image_url %></th>
  </tr>
     <tr>
         <th><%= f.label(:user_id, "User") %></th>
    <td><%= f.select(:user_id, @user.collect {|s| [s.email, s.id]}) %></td>
    </tr>
</table>
<div class="form-buttons">
		<h3><%= submit_tag("Update")%><h3>
	</div>
<%end%>
</div>

</div>
</div>

app/views/project/new.html.erb
<!--<div id= "navi">
  <div id="aside">
    <h1>project</h1>
   <b contenteditable data-title="Your company Task:">Add tasks</b><br />
     <a>Your company Task:<div id="debug"></div></a>
</div>
-->
<%= simple_form_for(@project) do |f|%>
<%= f.input :project_name%>
<%= f.text_field :estimeted_complete_date%>
<%= f.input :resources%>
<%= f.input :project_manager_name%>
<%= f.input :cost%>
<%= f.file_field :image%>
<%= f.select(:user_id, @user.collect {|s| [s.email, s.id]})%>

<%end%>

 <!--   
<div id="/background">
<div class="project">
  <a href="#" id="button">Create a new project</a>
    <div id="output"></div>
  
  <div id="overlay" class="web_dialog_overlay"> </div>
  <div id="popup" class="web_dialog">
	<%= simple_form_for(:project, :url => {:action => 'create'}) do |f| %>
	<table>
 
	<tr>
		<th>Project Name</th>
		<td><%= f.text_field(:project_name)%></td>
	</tr>
	<tr>
      <th><%= f.label (:estimated_complete_date)%></th>-->
     <!-- <td><%= datepicker_input "f","estimeted_complete_date", :class => 'ui-timepicker-div'%> </td>-->
       <!-- <td><%= f.text_field :estimeted_complete_date,:id => 'estimeted_complete_date'%></td>
     
    </tr>
    <tr>
    	 <th>People Involvement</th>
    	 <td><%= f.text_field(:resources)%></td>
    </tr>
    <tr>
    	 <th>Project Manager Name</th>
    	 <td><%= f.text_field(:project_manager_name)%></td>
    </tr>
    <tr>
    	 <th>Cost</th>
    	 <td><%= f.text_field(:cost)%></td>
	</tr>
       <tr>
         <th>Upload</th>
         <td><%= f.file_field :image %></td>
    </tr> 
      <tr>
    <th><%= f.label :remote_image_url, "or image URL" %></th>
    <th><%= f.text_field :remote_image_url %></th>
  </tr>
     <tr>
         <th><%= f.label(:user_id, "User") %></th>
    <td><%= f.select(:user_id, @user.collect {|s| [s.email, s.id]}) %></td>
    </tr>
</table>
<div class="form-buttons">
		<h3><%= submit_tag("Create")%><h3>
	</div>
<%end%>
<input id="btnSubmit" type="button" value="Submit" /> or <input id="close" type="button" value="Close" />
  </div>
</div>
</div>


-->

app/views/project/project_name.html.erb
<p>
  <b>Text:</b>
  <%= best_in_place @project, :project_name %>
</p>

<div class="aside" id="aside">

<p><%= link_to "back to project", :controller => 'project', :action => 'index'%></p>
    <% @projects.each do |f| %>
    <tr>
            <h1 id="/spacing"><a><%= f.project_name %></a></h1>

        </tr> 
         <%end%>


  <p id="topics">Project Topics:</p>
         
  <div class="project_topics" id="project_topics">
    <table>
    <tr>
      <ul>
      <% @topics.each do |topic| %>
    
       <li id=""><%= best_in_place topic,:topic_name%>: <%= pluralize topic.discussions.size,'discussion'%>,<%= pluralize topic.todos.size,'todo'%></li>

        <%end%>
      </ul>
    </tr>
  </table>
  <div id="test"><a>Create Topics</a></div>
          <div id="new">
             <%= form_for :topic, :url => {:action => 'create_topics'},:project_id => @project,:html => {:id => 'new_input' } do |f| %>
               <a id="hide"><%= f.select(:project_id, @projects.collect {|s| [s.id]})%></a>
   
               <%= f.text_field(:topic_name)%>
               <%= f.submit "Create"%>
               
                <%end%>
                <div id="cancel">
                   <a>or cancel</a>
                  </div>
                </div>
    </div>




    </tr>

  <p id="inbox">inbox:</p>
  <ul id="MenuBar2" class="MenuBarHorizontal">
    <li><a class="MenuBarItemSubmenu" href="#">Project Type:</a>
      <ul>
        <li><a href="#"> Personal</a></li>
        <li><a href="#">Workspace</a></li>
</ul>
    </li>
</ul>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
  <p>&nbsp; </p>
  <ul id="MenuBar1" class="MenuBarHorizontal">
    <li><a class="MenuBarItemSubmenu" href="#">Company Undertaking Project Name</a>
      <ul>
          <!--<% @project_undertaken.each do |f|%>
          <li><a href="#"><%= f.project_name%></li>
          <%end%>-->
      </ul>
    </li>
</ul>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
  <div class="project_details" >
    <p id="project_details">project details:    </p>

    <!-- filter -->
    <div id="show_details">
    <p href="#" id="button">add filter:</p>
      <div id="overlay" class="web_dialog_overlay"> </div>
                    <div id="popup" class="web_dialog">
                      <h1>Add filter to <a id="topic_filter">topics</a>,<a id="discussion_filter">discussions<a>,<a id="todos_filter">todos</a></h1>
                      <%= form_for :topic, :url => {:action => 'create_topics'},:project_id => @project,:html => {:id => 'new_input' } do |f| %>
                         <%= f.select(:project_id, @topics.collect {|s| [s.topic_name]})%>  
                         <%end%>       
                    </div>

    <!-- add persons -->
    <div class="persons" id="persons3">
           <p><a href="#">people involved: </a> 
                 <li><%= image_tag current_user.image_url(:thumb).to_s%><%= current_user.first_name + " " + current_user.last_name%></li>
                 
                          <% @add_users.each do |f|%>
                        <li>    <%= f.add_more_user%> </li>

                          <%end%>
                 

                 <a href="#" id="button1">Add more </a>
                    
                    <div id="overlay" class="web_dialog_overlay"> </div>
                    <div id="popup" class="web_dialog">
                    <%= render :partial => 'newuser' %>
                   <input id="close" type="button" value="Close" />
                    </div>
          </p>

    </div>
  </div>
 
</div>

  <script type="text/javascript">
var MenuBar1 = new Spry.Widget.MenuBar("MenuBar1", {imgDown:"SpryAssets/SpryMenuBarDownHover.gif", imgRight:"SpryAssets/SpryMenuBarRightHover.gif"});
var MenuBar2 = new Spry.Widget.MenuBar("MenuBar2", {imgDown:"SpryAssets/SpryMenuBarDownHover.gif", imgRight:"SpryAssets/SpryMenuBarRightHover.gif"});
</script>




<div id="main_content" class="main_content">
  <!--<span class="main_content"><br />-->
   <table>
    <ul>
     
      <li><h1>Topic Name</h1></li>
           <div id="search">
         <%= form_for :project do %>
          <p>
          <%= text_field_tag :query, params[:query]%>
          <%= submit_tag "Search topics,text-documents,todos,discussions,files", :name => :nil%>
          </p>
          <%end%>
        </div>
    
    <% @topics.each do |topic| %>
    <tr>
      
      <th  id="/topic_list"><li><b id="/click_topic"><h1><%= best_in_place topic,:topic_name %> </h1><%= topic.id%></b>
        <a><%= link_to 'See this Events in Calendar',:controller => 'calendar',:action => 'index'%></a>
                <%= form_for :topic do |f|%>
                <p>Attach text document<%= f.file_field(:add)%></p>
                <%end%>
      </li></th> 


        <tr>
            <th>
              <hr>
                            <h1>Discussions</h1>
                             
                                   <p><%= nested_messages topic.discussions.arrange(:order => :created_at) %></p>
                                  

                                    <br />

                                    <p><%= render :partial => 'shared/discussion',:topic_id => topic%></p>


            <!--  <table>
                <ul>
              
                <li><a>Discussions:</a></li><br />
                        <% topic.discussions.each do |discussion| %>
                          <ul id="discussion_block">
                            <li id="discussion_block_image">
                           <li><%= image_tag current_user.image_url(:thumb).to_s%> </li>
                            <li><%= current_user.first_name%></li>
                         </li>
                         <li id="/discussion_block_text">
                              <b ccontenteditable data-title=""><%= best_in_place discussion, :name %></b>  <a><%= discussion.created_at %></a> <a id="reply"><%= link_to 'Reply',:controller => 'discussion',:action => 'index', :parent_id => discussion%></a>
                              <%= link_to 'Reply',new_discussion_path(:parent_id => discussion)%></a>
                          </li>
                        </ul>-->
               <!-- add discussions 

                       <%end%>-->
           


             <!--     <li id="/more"></li> 
                    <li>
                     <%= link_to_function 'Add more discussion:',"jQuery('#more').append('#{escape_javascript render(:partial => 'shared/discussion',:object =>Discussion.new)}')" %>
                     </li>-->
           
             <!-- </ul>
           
              </table>


              <li><%= render :partial => 'shared/discussion'%></li>
            </th>
</tr>-->
 <tr>
             <th>
              <table>
                <ul>
              
                <li><a>Todos:</a></li><br />
                 <li>Completed</li>
                 <ul>
                       <% if @todo.status =  true%>
                      <% topic.todos.each do |todo| %>
                     <li> <%= best_in_place todo,:add %></li>
                     <%end%>
                     <%end%>
             </ul>
                 <li>Notcompleted</li>
                 <% topic.todos.each do |todo| %>
                 <%= form_for :todo,:url => {:action => 'save_todo'} do |f|%>
               <li>
                <b><%= f.select(:priority, 1..3) %></b> 
                <b><%= f.check_box(:status) %></b> 
                <b><%= todo.priority %></b> 
                <b ccontenteditable data-title=""><%= best_in_place todo,:add %></b>  <a>&nbsp</a> <b>Attach a file with todo <%= f.file_field(:add)%></b>  
                <%= f.submit "Save"%>
                      </li>
                      <%end%>
                 <%end%>
        
              </ul>
           
              </table>
                 
              <li> <%= render :partial => 'shared/todo'%></li>
                </div>
                </div>
          </th>
            </tr>

          </tr>
    <% end %>
  </table>
  </ul>
<h1>Text Documents</h1><%= form_for(:project, :url => {:action => 'create'})  do |f|%>
                        <td><%= f.file_field :image %></td>
                        <%= f.submit%>
                        <%end%>
<% @projects.each do |f|%>
<td><%= link_to h(image_tag f.image_url(:thumb).to_s),:controller => 'project',:action => 'document'%> <a>text document</a></td>

<%end%>
 <!--</span>-->
  <div class="inbox_display" id="inbox_display">Content for  class "inbox_display" id "inbox_display" Goes Here</div>
</div>








<!--
<hr>

   <table class="/listing" summary="project list">
    <tr class="header">
     <th>Topic</th>      
      <th> 
        <div id="test"><a>Create Topics</a></div>
          <div id="new">
             <%= form_for :topic, :url => {:action => 'create_topics'},:project_id => @project,:html => {:id => 'new_input' } do |f| %>
               <a id="hide"><%= f.select(:project_id, @projects.collect {|s| [s.id]})%></a>
   
               <%= f.text_field(:topic_name)%>
               <%= f.submit "Create"%>
               
                <%end%>
                <div id="cancel">
                   <a>or cancel</a>
                  </div>
                </div>
              </th>


    </tr>
    <% @topics.each do |topic| %>
    <tr>
       <td id="topic" onmouseover="/call()" contenteditable data-name="title"><%= topic.topic_name%></td>
       <td id="debug"></td>-->

                        <!--
                     <% @projects.each do |f|%>
                  
                      <ul id="show_discussion"> <%= link_to ("Add Discussions"),{:controller => 'discussion', :action => 'view', :project_id => f.id, :method => :post}, :class => 'action show'%>
                           
                  <%= link_to ("To do list"),{:controller => 'todo', :action => 'new', :project_id => f.id}, :class => 'action show'%>
                       <%= link_to ("Delete topics"),{ :action => 'delete', :project_id => f.id}, :class => 'action delete'%>   </ul>  
                         <%end%>--> 
   <!--       <tr>
            <th>
              <hr>
              <table>
                <ul>
              
                <li><a>Discussions:</a></li><br />
                 <% topic.discussions.each do |discussion| %>
               <li><b contenteditable data-title=""><%= discussion.started_by %><%= discussion.name %></b> | <%= discussion.created_at %> </li>-->
               <!-- add discussions -->

         <!--     <%end%>-->
           


             <!--     <li id="/more"></li> 
                    <li>
                     <%= link_to_function 'Add more discussion:',"jQuery('#more').append('#{escape_javascript render(:partial => 'shared/discussion',:object =>Discussion.new)}')" %>
                     </li>-->
           
          <!--    </ul>
           
              </table>-->
              <!-- <div id="add_discussion"><a>Add Discussions</a></div>
          <div id="new_discussion">-->
             <!-- <li><% render :partial => 'shared/discussion'%></li>-->
           <!--      <div id="cancel_discussion">
                   <a>or cancel</a>
                  </div>
                </div>-->
      <!--      </th>
</tr>
                 <tr>
             <th>
              <table>
                <ul>
              
                <li><a>Todos:</a></li><br />
                 <% topic.todos.each do |todo| %>
               <li>
                <b><%= check_box_tag(:visible) %></b> 
                <b><%= todo.priority %></b> 
                <b contenteditable data-title=""><%= todo.add %></b>  <a>&nbsp</a><a>Attach a file with todo</a> </li> 
                 <%end%>
        
              </ul>
           
              </table>-->
              <!--   <div id="add_topic"><a>Add Topics</a></div>
          <div id="new_topic">-->
               <% render :partial => 'shared/todo'%>
              <!--   <div id="cancel_topic">
                   <a>or cancel</a>
                </div>
                </div>-->
         <!--   </th>
            </tr>



            </tr>
    
    <% end %>
  </table>

  <hr>

<%= render :partial => 'document'%>-->

app/views/project/show.html.erb
<!--code for going home -->
<%= form_for(:project, :url => {:action => 'home'}) do |f| %>
<%= render(:partial => "shared/main", :locals => {:f => f})%>
<%end%>

<%= link_to("Back to new project", {:action => 'new'})%>

<table class="mercury-region" data-type="editable">
    <tr class="header">
	   <th>&nbsp</th>
        <th>&nbsp</th>
        <th>Project Name</th>
        <th>Estimeted Complete Date</th>
        <th>Done</th>
        <th>Resources</th>
        <th>Project Manager Name</th>
        <th>Cost</th>
    </tr>
  
        <% @project.each do |f|%>
            <tr>
                <td><%= f.username%></td>
                 <td><%= f.user_id%></td>
                <td><%= best_in_place f,:project_name%></td> 
               
                <td><%= f.estimeted_complete_date%></td> 
              
               <td class="center"><%= status_tag(f.done) %></td> 

            
                <td><%= f.resources%></td>
           
                <td><%= f.project_manager_name%></td>
            
                <td><%= f.cost%></td>
                 <td><%= image_tag f.image_url(:thumb).to_s%></td>

                <td class="actions">
                    <!--<%= link_to "Edit Page","/editor" + request.path%>-->
            <%= link_to "Edit",{:action => 'edit', :id => f.id}, 
             :class => 'action edit'%>
               <%= link_to "Delete",{:action => 'delete', :id => f.id}, 
             :class => 'action delete'%>
            </td>
            </tr>
            
    <%end%>
</table>
</div>
	